<?php

namespace AppBundle\Repository;

/**
 * CarrouselRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarrouselRepository extends \Doctrine\ORM\EntityRepository
{
}
