<?php

namespace AppBundle\Repository;

/**
 * DediRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DediRepository extends \Doctrine\ORM\EntityRepository
{
}
